---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kener.fullname" . }}-env
type: Opaque
stringData:
  {{ if .Values.envs.githubToken }}
  GH_TOKEN: {{ .Values.envs.githubToken}}
  {{ end }}
  {{ if .Values.envs.apiToken  }}
  API_TOKEN: {{ .Values.envs.apiToken }}
  {{ end }}
  {{ if .Values.envs.apiIP }}
  API_IP: {{ .Values.envs.apiIP }}
  {{ end }}
  {{ if .Values.envs.apiIPRegex }}
  API_IP_REGEX: {{ .Values.envs.apiIPRegex }}
  {{ end }}
